E-Health-Care-master/Disease/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/',include('api.urls')),
    path('doctor/',include('doctor.urls')),
    path('roleadmin/',include('roleadmin.urls')),
    path('patient/',include('patient.urls')),
    path('health/',include('Health.urls')),
    path('', RedirectView.as_view(url="health/")),
]
urlpatterns=urlpatterns+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



admin.site.site_header = 'Smart Health'                    # default: "Django Administration"
admin.site.index_title = 'Features area'                 # default: "Site administration"
admin.site.site_title = 'HTML title from adminsitration' # default: "Django site admin"

E-Health-Care-master/api/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf.urls import url
from django.views.generic.base import RedirectView
from rest_framework import routers
from api import views

router=routers.DefaultRouter()

router.register(r'api', views.DiseaseViewSet)
#router.register(r'auth', views.UserViewSet)

urlpatterns=[
    path(r'api/', include(router.urls)),
    path('',RedirectView.as_view(url="api/"))
]

E-Health-Care-master/patient/urls.py
from django.contrib import admin
from django.urls import path,include
from patient import views
from django.views.generic.base import RedirectView

urlpatterns = [        
path('patient/',RedirectView.as_view(url='patient_login/')),
path('patient_login/', views.patient_login,name='patient_login'),
path('patient_register/', views.patient_register,name='patient_register'),
path('patient_profile/',views.patient_profile,name='patient_profile'),
path('my_profile/',views.my_profile,name="my_profile"),

path('form/', views.form, name="form"),

path('search_doctor/', views.search_doctor,name="search_doctor"),
path('search_doctor/doctor_profile/<int:pk>',views.doctor_profile),
#path('update_profile/',views.patient_update,name='update_profile'),
path('dashboard/', views.dashboard, name="dashboard"),

path('home/',views.home,name="home"),
path('home/doctor_profile/<int:pk>',views.doctor_profile),
path('feedback/',views.feedback,name="feedback"),
path('feedback/detail/<int:pk>',views.feedback_detail),
path('feedback/edit/<int:pk>',views.feedback_edit),
path('feedback/add_feedback',views.feedback_add),
path('feedback/delete/<int:pk>',views.feedback_delete),

# path('check/', views.check, name="check"),
path('logoutpatient/', views.logoutpatient, name="logoutpatient"),

path('heart/', views.heart, name="heart"),
path('Diabetes/', views.Diabetes, name="Diabetes"),

path('showimage/', views.showimage, name="showimage"),

]

E-Health-Care-master/patient/models.py
from django.db import models
from django.core.validators import MinLengthValidator, RegexValidator
from django.db.models import CASCADE
from django.contrib.auth.models import User
#from patient.models import PatientInfo
from django.db.models.signals import post_save
from django.db.models import signals
from django.dispatch import receiver
from doctor.models import *

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    name=models.CharField(max_length=20)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    phone_number = models.CharField(validators=[phone_regex], max_length=17, blank=True) # validators should be a list
    address=models.CharField(max_length=40)
    gender=models.CharField( max_length=50,blank=True,choices=(('Female','Female'),('Male','Male'),('Other','Other')))
    age=models.IntegerField(blank=True , null=True)
    status=models.CharField(max_length=20,blank=True,choices=(('Single','Single'),('Married','Married')))
    profile_pic=models.ImageField(blank=True,null=True)

    def __str__(self):
        return self.name

@receiver(post_save,sender=User)
def create_user_profile(sender,instance,created,**kwargs):
	if created:
		Profile.objects.create(user=instance,name=instance.username)


@receiver(post_save,sender=User)
def save_user_profile(sender,instance,**kwargs):
	instance.profile.save()

# when profile is deleted user is also delete
def delete_user(sender, instance=None, **kwargs):
    try:
        instance.user
    except User.DoesNotExist:
        pass
    else:
        instance.user.delete()
signals.post_delete.connect(delete_user, sender=Profile)

class Feedback(models.Model):
    text=models.TextField(max_length=200)
    title=models.CharField(max_length=50)
    picture=models.ImageField()
    date=models.DateTimeField(auto_now_add=True)
    uploaded_by=models.ForeignKey(Profile,on_delete=models.CASCADE)
    def __str__(self):
        return self.title

class WhoPredictDisease(models.Model):
    predict_by=models.ForeignKey(Profile,on_delete=models.CASCADE)
    predicted_disease=models.CharField(max_length=30)
    # def __str__(self):
    #     return "Profile"
    # name=models.CharField(max_length=20)
    # email=models.CharField(max_length=30,blank=True)
    # phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    # phone_number = models.CharField(validators=[phone_regex], max_length=17, blank=True) # validators should be a list
    # predicted_disease=models.CharField(max_length=50)
    #who_predict=models.OneToOneField(Profile,on_delete=models.CASCADE)

class Disease1(models.Model):
    name=models.CharField(max_length=200)
    doctor=models.ForeignKey(DoctorInfo,on_delete=models.CASCADE,null=True)
    # doctor=models.ManyToManyField(DoctorInfo)
    # doctor_name=models.ManyToManyField(on_delete= CASCADE, to=DoctorInfo)
    def __str__(self):
        return self.name 

# Create your models here.
class Heart(models.Model):
    age=models.IntegerField()
    sex=models.IntegerField()
    cp=models.IntegerField()
    trestbps=models.IntegerField()
    chol=models.IntegerField()
    fbs=models.IntegerField()
    restecg=models.IntegerField()
    thalach=models.IntegerField()
    exang=models.IntegerField()
    oldpeak=models.IntegerField()
    slope=models.IntegerField()
    ca	=models.IntegerField()
    thal=models.IntegerField()
    def to_dict(self):
        return{
            'age':self.age,
            'sex':self.sex,
            'cp':self.cp,
            'trestbps':self.trestbps,
            'chol':self.chol,
            'fbs':self.fbs,
            'restecg':self.restecg,
            'thalach':self.thalach,
            'exang':self.exang,
            'slope':self.slope,
            'oldpeak':self.oldpeak,
            'ca':self.ca,
            'thal':self.thal,

        }

class Diabetes(models.Model):
    Pregnancies=models.IntegerField()
    Glucose=models.IntegerField()
    BloodPressure=models.IntegerField()
    SkinThickness=models.IntegerField()
    Insulin=models.IntegerField()
    BMI=models.IntegerField()
    DiabetesPedigreeFunction=models.IntegerField()
    Age=models.IntegerField()
    
    def to_dict(self):
        return{
            'Pregnancies':self.Pregnancies,
            'Glucose':self.Glucose,
            'BloodPressure':self.BloodPressure,
            'SkinThickness':self.SkinThickness,
            'Insulin':self.Insulin,
            'BMI':self.BMI,
            'DiabetesPedigreeFunction':self.DiabetesPedigreeFunction,
            'Age':self.Age,
        }

class Image(models.Model):
    # name= models.CharField(max_length=500)
    imagefile= models.FileField(upload_to='images/', null=True, verbose_name="")
    # def __str__(self):
    #     return self.name + ": " + str(self.imagefile)
    

E-Health-Care-master/patient/views.py
from django.shortcuts import render, redirect
from patient.forms import *
from django.contrib.auth import authenticate, logout, login
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from patient.models import Profile
from django.db import transaction
from patient.models import *
# Create your views here.

from django.shortcuts import render, HttpResponse
import requests

from Health.forms import *
from api.models import Disease
from api import diseaseml
# from . import heart
from patient.heart import pred_heart
from patient.Diabetes import pred
from patient.pneumonia import pred1
from api.diseaseml import pred
from .models import Image
from django.contrib.auth.models import Group

from django.db.models import Q
# Pagination import
# from django.core.paginator import Paginator,PageNotAnInteger,EmptyPage
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


@login_required(login_url='patient_login')
# for Pnemonia check
def showimage(request):

    lastimage = Image.objects.last()
    imagefile = lastimage.imagefile
    form = ImageForm(request.POST or None, request.FILES or None)
    contex = {'form': form}
    if form.is_valid():
        form.save()
        lastimage = Image.objects.last()
        imagefile = lastimage.imagefile
        print(imagefile)
        sur = pred1(imagefile)
        context = {
            'imagefile': imagefile,
            'form': form,
            'sur': sur,
        }
        return render(request, 'patient/image.html', context)
    sur = ' '
    context = {
        'imagefile': imagefile,
        'form': form,
        'sur': sur,
    }
    return render(request, 'patient/image.html', context)


@login_required(login_url='patient_login')
# For Diabetes Disease Prediction
def Diabetes(request):
    if request.method == "GET":
        diabetes_form = DiabetesForm()
        contex = {
            'diabetes_form': diabetes_form
        }
        return render(request, 'patient/diabetes.html', contex)
    elif request.method == "POST":
        diabetes_form = DiabetesForm(request.POST)
        if diabetes_form.is_valid:
            diabetes_form.save()
            from patient.models import Diabetes
            ob = Diabetes.objects.latest('id')
            print(ob)
            sur = pred(ob)
            sur = ", ".join(repr(e) for e in sur).strip("''")
            if sur == '1':
                name = "Yes, You are suffering  from Diabetes problems"
                disease_name = "Diabetes"
                # saving  user information who predict disease and suggesting doctors
                predict = WhoPredictDisease(
                    predict_by=request.user.profile, predicted_disease=disease_name)
                predict.save()
                disease = Disease1.objects.filter(name__icontains=disease_name)
                listDoctorID = []
                for d in disease:
                    listDoctorID.append(d.doctor.id)
                disease_doctor_list = DoctorInfo.objects.filter(
                    Q(id__in=listDoctorID))
                context = {
                    'sur': 'You are suffering from diabetes problem',
                    'disease_doctor_list': disease_doctor_list,
                }
            elif sur == '0':
                context = {
                    'sur': 'You are not suffering from diabetes problem',
                    # 'disease_doctor_list':disease_doctor_list
                }
            return render(request, 'patient/diabetes_results.html', contex)
        # else:
        #     return render(request,'patient/diabetes.html',context)
        #     pass


@login_required(login_url='patient_login')
# For heart Disease predicton
def heart(request):
    if request.method == "GET":
        heart_form = HeartForm()
        contex = {
            'heart_form': heart_form
        }
        return render(request, 'patient/heart.html', contex)
    elif request.method == "POST":
        heart_form = HeartForm(request.POST)

        if heart_form.is_valid:
            heart_form.save()
            ob = Heart.objects.latest('id')
            sur = pred_heart(ob)
            sur = ", ".join(repr(e) for e in sur).strip("''")

            if sur == '1':
                name = "Yes, You are suffuring from heart problem"
            elif sur == '0':
                name = "You are not suffuring from heart problme"

            contex = {
                'sur': name,
            }
            return render(request, 'patient/heart_results.html', contex)


@login_required(login_url='patient_login')
# Disease prediction as well dashboard !!
def dashboard(request):
    if request.method == "POST":
        contex = {}
        if request.POST.get('value1'):
            disease = Disease()
            value1 = request.POST.get('value1')

            value2 = request.POST.get('value2')

            value3 = request.POST.get('value3')

            value4 = request.POST.get('value4')

            value5 = request.POST.get('value5')

            value6 = request.POST.get('value6')

            disease.value_1 = value1
            disease.value_2 = value2
            disease.value_3 = value3
            disease.value_4 = value4
            disease.value_5 = value5
            disease.value_6 = value6
            disease.save()
            ob = Disease.objects.latest('id')
            sur = pred(ob)
            predicted_disease_name = sur[0][0]
            symptoms = sur[1]

            value1 = symptoms[0]
            value2 = symptoms[1]
            value3 = symptoms[2]
            value4 = symptoms[3]
            value5 = symptoms[4]
            value6 = symptoms[5]

            # patient who predrict disease is save in now database
            predict = WhoPredictDisease(
                predict_by=request.user.profile, predicted_disease=predicted_disease_name)
            predict.save()
            disease = Disease1.objects.filter(
                name__icontains=predicted_disease_name)
            listDoctorID = []
            for d in disease:
                listDoctorID.append(d.doctor.id)
            disease_doctor_list = DoctorInfo.objects.filter(
                Q(id__in=listDoctorID))

        return render(request, 'patient/showDisease.html', context={"Predicted_disease": predicted_disease_name, 'disease_doctor_list': disease_doctor_list, "value1": value1, 		"value2": value2, "value3": value3, "value4": value4, "value5": value5, "value6": value6})

    else:
        return render(request, 'patient/dashboard.html')


@login_required(login_url='patient_login')
def form(request):
    pass


@login_required(login_url='patient_login')
def feedback(request):
    page = request.GET.get('page', 1)
    feedbacks = Feedback.objects.filter(
        Q(uploaded_by=request.user.profile)).order_by('-id')
    paginator = Paginator(feedbacks, 8)
    try:
        feedbacks = paginator.page(page)
    except PageNotAnInteger:
        feedbacks = paginator.page(1)
    except EmptyPage:
        feedbacks = paginator.page(paginator.num_pages)
    context = {
        'feedbacks': feedbacks
    }
    return render(request, 'patient/feedback.html', context)


@login_required(login_url='patient_login')
def feedback_detail(request, pk):
    feedback = Feedback.objects.get(id=pk, uploaded_by=request.user.profile)
    print(feedback)
    context = {
        "feedback": feedback
    }
    return render(request, 'patient/feedback_detail.html', context)


@login_required(login_url='patient_login')
def feedback_delete(request, pk):
    try:
        feedback = Feedback.objects.get(
            id=pk, uploaded_by=request.user.profile)
    except:
        return redirect('feedback')
    feedback.delete()
    return redirect('feedback')


@login_required(login_url='patient_login')
def feedback_edit(request, pk):
    try:
        feedback = Feedback.objects.get(
            id=pk, uploaded_by=request.user.profile)
    except:
        return redirect('feedback')
    if request.method == 'POST':
        feedback_edit_form = FeedbackForm(
            request.POST or None, request.FILES, instance=feedback)
        if feedback_edit_form.is_valid():
            update = feedback_edit_form.save(commit=False)
            update.uploaded_by = request.user.profile
            update.save()
            return redirect('feedback')
        else:
            context = {
                'feedback_edit_form': feedback_edit_form,
                'feedback': feedback
            }
            return render(request, 'patient/feedback_edit_form.html', context)
    else:
        feedback_form = FeedbackForm(
            request.POST or None, request.FILES, instance=feedback)
        context = {
            'feedback_form': feedback_form,
            'feedback': feedback
        }
        return render(request, 'patient/feedback_edit_form.html', context)


@login_required(login_url='patient_login')
def feedback_add(request):
    if request.method == 'POST':
        feedback_add_form = FeedbackForm(
            request.POST or None, request.FILES or None)
        if feedback_add_form.is_valid():
            add_feedback = feedback_add_form.save(commit=False)
            add_feedback.uploaded_by = request.user.profile
            add_feedback.save()
            return redirect('feedback')
        else:
            context = {
                'feedback_add_form': feedback_add_form
            }
            return render(request, 'patient/feedback_add_form.html', context)
    else:
        feedback_add_form = FeedbackForm()
        context = {
            'feedback_add_form': feedback_add_form
        }
        return render(request, 'patient/feedback_add_form.html', context)


@login_required(login_url='patient_login')
def search_doctor(request):
    context = {}
    if request.method == "POST":
        search_term = request.POST.get('term')

E-Health-Care-master/patient/templates/patient/dashboard.html
{% extends "base.html" %}

{% block body_content %}

<div class="page-wrapper">
  <div class="content">
              <div class="row">
                  <div class="col-sm-12">
                      <h4 class="page-title"><strong>Please, choose at least 6 symptoms for prediction your disease.</strong></h4>
                  </div>
              </div>
          <div class="card-box" style="background-color: skyblue;">
     
         
    <form method="POST" action="/patient/dashboard/" enctype="multipart/form-data">
      {% csrf_token %}
       
         <h3 class="card-title"></h3>
         <!-- $('select').selectpicker(); -->
        
        <h4>symptoms 1</h4>
        <select class="selectpicker" name = 'value1' >
          <option>receiving_blood_transfusion</option>
          <option>red_sore_around_nose</option>
          <option>abnormal_menstruation</option>
          <option>continuous_sneezing</option>
          <option>breathlessness</option>
          <option>blackheads</option>
          <option>shivering</option>
          <option>dizziness</option>
          
        </select>

        <br>
        <br>
        <h4>symptoms 2</h4>
        <select class="selectpicker" name = 'value2'>
          <option>back_pain</option>
          <option>unsteadiness</option>
          <option>yellow_crust_ooze</option>
          <option>muscle_weakness</option>
          <option>loss_of_balance</option>
          <option>chills</option>
          <option>ulcers_on_tongue</option>
          <option>stomach_bleeding</option>
        
        </select>
        <br>
        <br>
        <h4>symptoms 3</h4>
        <select class="selectpicker" name = 'value3'>
          <option>lack_of_concentration</option>
          <option>coma</option> 
          <option>neck_pain</option>
          <option>weakness_of_one_body_side</option>
          <option>diarrhoea</option>
          <option>receiving_unsterile_injections</option>
          <option>headache</option>
          <option>family_history</option>
        </select>
        <br>
        <br>
        <h4>symptoms 4</h4>
        <select class="selectpicker" name = 'value4' >
          <option>fast_heart_rate</option>
          <option>pain_behind_the_eyes</option>
          <option>sweating</option>
          <option>mucoid_sputum</option>
          <option>spotting_urination</option>
          <option>sunken_eyes</option>
          <option>dischromic_patches</option>
          <option>nausea</option>
          
        </select>
        <br>
        <br>
        <h4>symptoms 5</h4>
        <select class="selectpicker" name ='value5'>
          <option>dehydration</option>
          <option>loss_of_appetite</option>
          <option>abdominal_pain</option>
          <option>stomach_pain</option>
          <option>yellowish_skin</option>
          <option>altered_sensorium</option>
          <option>chest_pain</option>
          <option>muscle_wasting</option>
        </select>
        <br>
        <br>
        <h5>symptoms 6</h5>
        <select class="selectpicker" name = 'value6'>
          <option>vomiting</option>
          <option>mild_fever</option>
          <option>high_fever</option>
          <option>red_spots_over_body</option>
          <option>dark_urine</option>
          <option>itching</option>
          <option>yellowing_of_eyes</option>
          <option>fatigue</option>
          <option>joint_pain</option>
          <option>muscle_pain</option>
        </select>
        <br>
        <br>
        <br>

          <!-- {{disease_form.as_p}} -->
         
          <button type="Check" class="btn btn-primary btn-user "> Check</button>


          </form>
          
         
              
    </div>
    </div>
    </div>


 
  {% endblock %}

E-Health-Care-master/patient/templates/patient/diabetes.html
{% extends "base.html" %}
{% block body_content %}

<div class="page-wrapper">
    <div class="content">
        <div class="row">
            <div class="col-sm-12">
                <h4 class="page-title">Diabetes check up</h4>
                <h4 class="page-title">Enter the following parameters:</h4>
            </div>
            <form method="POST" action="" enctype="multipart/form-data">
                {% csrf_token %}
                {{diabetes_form.as_p }}
                <button type="Check" class="btn btn-primary btn-user "> Check</button>
            </form>
    
        </div><br><br>
        <div class="col-sm-12">
            <h4 class="page-title">Diabetes parameters information</h4>
           
        </div>
        <h5>Pregnancies : Number of times pregnant </h5>
        <h5>Glucose : Plasma glucose concentration a 2 hours in an oral glucose tolerance test</h5>
        <h5>BloodPressure : Diastolic blood pressure (mm Hg)</h5>
        <h5>SkinThickness : Triceps skin fold thickness (mm)</h5>
        <h5>Insulin : 2-Hour serum insulin (mu U/ml) </h5>
        <h5> BMI : Body mass index (weight in kg/(height in m)^2) </h5>
        <h5>DiabetesPedigreeFunction : Diabetes pedigree function </h5>
        <h5>Age : Age (years)</h5>
    </div>
</div>
{% endblock %}

E-Health-Care-master/patient/templates/patient/feedback_add_form.html
{% extends 'base.html' %}
{% load static %}
{% block body_content %}
<div class="page-wrapper">
<div class="content"> 
    <div class="row">
            <h4 class="page-title">Add Feedback</h4>
    </div>
    <!-- <div class="row"> -->
            <form method="POST" action="" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_title">Title:</label>
                 <input class="form-control" type="text" name="title"  maxlength="50" required id="id_title">
                </div>
            <div class="form-group">
                <label for="id_text">Description</label> 
                <textarea class="form-control" name="text" cols="40" rows="10" maxlength="200" required id="id_text">
                </textarea>
                </div>
           
        <div class="form-group">
             <label for="id_picture">Picture Currently:</label> <a href="feedback.picture.url"></a><br>
                <input value="feedback.picture.url" class="form-control" type="file" name="picture" accept="image/*" id="id_picture">
        </div> 
        <button type="submit" class="btn btn-info btn-user ">Update Feedback</button>         
        
        <a href="{% url 'feedback' %}" class="btn btn-secondary">Cancel</a>
    </form>
    <!-- </div> -->
</div>
</div>

{% endblock %}

E-Health-Care-master/patient/templates/patient/feedback_edit_form.html
{% extends 'base.html' %}
{% load static %}
{% block body_content %}
<div class="page-wrapper">
<div class="content"> 
    <div class="row">
            <h4 class="page-title">Update Feedback</h4>
    </div>
    <!-- <div class="row"> -->
            <form method="POST" action="" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_title">Title:</label>
                 <input class="form-control" type="text" name="title" value="{{feedback.title}}" maxlength="50" required id="id_title">
                </div>
            <div class="form-group">
                <label for="id_text">Description</label> 
                <textarea class="form-control" name="text" cols="40" rows="10" maxlength="200" required id="id_text">
                    {{feedback.text}}
                </textarea>
                </div>
           
        <div class="form-group">
             <label for="id_picture">Picture Currently:</label> <a href="feedback.picture.url">{{feedback.picture}}</a><br>
                <input value="feedback.picture.url" class="form-control" type="file" name="picture" accept="image/*" id="id_picture">
        </div> 
        <button type="submit" class="btn btn-info btn-user ">Update Feedback</button>         
        
        <a href="{% url 'feedback' %}" class="btn btn-secondary">Cancel</a>
    </form>
    <!-- </div> -->
</div>
</div>

{% endblock %}

E-Health-Care-master/patient/templates/patient/heart_results.html
{% extends "base.html" %}
{% block body_content %}

<div class="page-wrapper">
    <div class="content">
        <div class="row">
            <div class="col-sm-12">
                <h4 class="page-title">{{sur}}</h4>
            </div>
        </div>
    </div>
</div>
{% endblock %}

E-Health-Care-master/patient/templates/patient/profile.html
{% extends "base.html" %}

{% block body_content %}
        <div class="page-wrapper">
            <div class="content">
                <div class="row">
                    <div class="col-sm-12">
                        <h4 class="page-title">Edit Profile</h4>
                    </div>
                </div>
                   
<form method="POST" action="" enctype="multipart/form-data">
  {% csrf_token %}
   <div class="card-box">
                       <h3 class="card-title">My Informations</h3>
  <div class="form-group">
    <label for="id_email">Email address</label>&nbsp &nbsp
    <input class="form-control" value="{{request.user.email}}"  name="email"
      maxlength="254" id="id_email">
  </div>
  <br />
  <div class="form-group"><label for="id_name">Name</label>&nbsp &nbsp <input type="text" value="{{request.user.profile.name}}" name="name"
      maxlength="20" required id="id_name" class="form-control"></div>

  <br />
  <div class="form-group"><label for="id_phone_number">Phone number</label> &nbsp &nbsp<input type="text"
      class="form-control" value="{{request.user.profile.phone_number}}" name="phone_number" maxlength="17"
      id="id_phone_number"></div>
  <br />
  <div class="form-group"><label for="id_address">Address</label>&nbsp &nbsp <input
      value="{{request.user.profile.address}}" type="text" class="form-control" name="address" maxlength="40" required
      id="id_address"></div>
  <br />
  <div class="form-group"><label for="id_gender">Gender</label> &nbsp &nbsp<select class="form-control form-control-lg"
      value="{{request.user.profile.gender}}" name="gender" id="id_gender">\n <option readonly value="Female">Female
      </option>\n\n <option readonly value="Male" selected>Male</option>\n\n <option readonly value="Other">Other
      </option>\n\n</select></div>
  <br />
  <div class="form-group"><label for="id_age">Age</label> &nbsp &nbsp<input class="form-control" type="text" name="age"
      value="{{request.user.profile.age}}" maxlength="20" required id="id_age"></div>
  <br />
  <div class="form-group"><label for="id_status">Status</label> &nbsp &nbsp<select name="status" id="id_status"
      class="form-control form-control-lg">\n <option value="Single" selected>Single</option>\n\n <option
        value="Married">Married</option>\n\n</select></div><br />

  <div class="form-group"><label for="id_profile_pic">Profile Picture</label>
    <br />
    <br />
    <input class="form-control-file" type="file" name="profile_pic" accept="image/*" id="id_profile_pic" value="{{request.user.profile.profile_pic}}"></div>
  <br />


  <button type="submit" class="btn btn-primary btn-user "> Update Profile</button>

  <br />
  
  </div>
 
      
</form>
</div>
</div>


<!--
<h4 class="mb-5">My Profile</h4>
<div align="center">
   {% if request.user.profile.profile_pic.url != '' %}
  <img src="{{request.user.profile.profile_pic.url}}" alt="Images" height="300px"/>
  {% else %} 
  <i class="fas fa-10x fa-user-circle"></i>
  {% endif %}
</div>
<div class="card-body">
</div>

-->
<!--


<div  class="card text-white bg-secondary mb-3" >
  <div class="card-body">
  <div class="card-group">
    <br />

<form method="POST" action="" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="form-inline">
    <label for="id_email">Email address</label>&nbsp &nbsp
    <input class="form-control" value="{{request.user.email}}" style="width: 300px;" type="email" name="email"
      maxlength="254" id="id_email">
  </div>
  <br />
  <div class="form-inline"><label for="id_name">Name</label>&nbsp &nbsp <input type="text" value="{{request.user.profile.name}}" name="name"
      maxlength="20" required id="id_name" class="form-control"></div>

  <br />
  <div class="form-inline"><label for="id_phone_number">Phone number</label> &nbsp &nbsp<input type="text"
      class="form-control" value="{{request.user.profile.phone_number}}" name="phone_number" maxlength="17"
      id="id_phone_number"></div>
  <br />
  <div class="form-inline"><label for="id_address">Address</label>&nbsp &nbsp <input
      value="{{request.user.profile.address}}" type="text" class="form-control" name="address" maxlength="40" required
      id="id_address"></div>
  <br />
  <div class="form-inline"><label for="id_gender">Gender</label> &nbsp &nbsp<select class="form-control form-control-lg"
      value="{{request.user.profile.gender}}" name="gender" id="id_gender">\n <option readonly value="Female">Female
      </option>\n\n <option readonly value="Male" selected>Male</option>\n\n <option readonly value="Other">Other
      </option>\n\n</select></div>
  <br />
  <div class="form-inline"><label for="id_age">Age</label> &nbsp &nbsp<input class="form-control" type="text" name="age"
      value="{{request.user.profile.age}}" maxlength="20" required id="id_age"></div>
  <br />
  <div class="form-inline"><label for="id_status">Status</label> &nbsp &nbsp<select name="status" id="id_status"
      class="form-control form-control-lg">\n <option value="Single" selected>Single</option>\n\n <option
        value="Married">Married</option>\n\n</select></div><br />

  <div class="form-inline"><label for="id_profile_pic">Profile Picture</label>
    <br />
    <br />
    <input class="form-control-file" type="file" name="profile_pic" accept="image/*" id="id_profile_pic"></div>
  <br />
  <br />

  <button type="submit" class="btn btn-primary btn-user "> Update Profile</button>

  <br />
  <br />
</form>
</div>
  </div>
</div>

-->


{% endblock %}